### Import Numpy

In [2]:
import numpy as np

### Arrary creation

In [9]:
test_array = np.array([1, 4, 5, 8], float)
print(test_array)
type(test_array[3])

[ 1.  4.  5.  8.]


numpy.float64

In [11]:
test_array = np.array([1, 4, 5, 8], np.float32)
print(test_array)
type(test_array[3])

[ 1.  4.  5.  8.]


numpy.float32

In [15]:
test_array = np.array([1, 4, 5, "8"], float) # String Type의 데이터를 입력해도
test_array

array([ 1.,  4.,  5.,  8.])

In [16]:
type(test_array[3]) # Float Type으로 자동 형변환을 실시

numpy.float64

In [17]:
test_array.dtype # Array(배열) 전체으 데이터 Type을 반환함

dtype('float64')

### Value assignment 

In [20]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], int)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a[0,0]  # Two dimensional array representation #1

1

In [23]:
a[0,0] == a[0][0] # Two dimensional array representation #2

True

In [24]:
a[0,0] = 12 # Matrix 0,0 에 12 할당
a

array([[12,  2,  3],
       [ 4,  5,  6]])

In [26]:
a[0][0] = 5 # Matrix 0,0 에 12 할당
a

array([[5, 2, 3],
       [4, 5, 6]])

### Slicing

In [27]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
a[:,2:] # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [28]:
a[1,1:3] # 1 Row의 1열 ~ 2열

array([7, 8])

In [29]:
a[1:3] # 1 Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10]])

### Function

In [31]:
np.arange(30) # range: List의 range와 같은 효과, integer로 0부터 29까지 배열추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
np.arange(30).dtype  # dtype: 배열의 data type을 표시함

dtype('int32')

In [33]:
np.arange(30).reshape(5,6) 
# reshape(x,y) : 기존 배열을 row x, column y의 matrix - two dimensional array로 변경 (three도 가능)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [35]:
np.zeros(10) # 10 - zero vector 생성

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [36]:
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [38]:
np.zeros((2,5), np.float32) # 2 by 5 - zero matrix를 float32 type으로 생성

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [40]:
np.zeros((2,5)).ndim # 2 by 5의 matrix의 차원의 크기 (row 기준)

2

In [47]:
np.zeros((2,5)).shape # 2 by 5의 matrix의 전체 크기

(2, 5)

In [48]:
np.ones((5,5),float) # ones((x,y),type): x,y의 matrix를 생성하여 모든 초기값을 1로 설정

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [49]:
np.empty((5,5),float) # empty((x,y),type):  초기값을이 할당되지 않은 x,y의 matrix를 생성

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [54]:
np.eye(5,6) # eye((x,y)):  x by y의 matrix를 생성후 대각행렬에 1을 할당

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.]])

In [55]:
np.identity(5) # identity((x)):  x by x의 matrix를 생성후 대각행렬에 1을 할당

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

### Numpy operation - Matrix

In [56]:
test_a = np.array([[1,2,3],[4,5,6]], float)

In [57]:
test_a + test_a # Matrix + Matrix 연산

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [58]:
test_a - test_a # Matrix - Matrix 연산

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [59]:
test_a.transpose() # Matrix trnspose 연산 또는 test_a.T

array([[ 1.,  4.],
       [ 2.,  5.],
       [ 3.,  6.]])

In [60]:
test_a * test_a # Matrix내 element들 간 같은 위치에 있는 값들끼리 연산

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [61]:
test_a.T.dot(test_a) # Matrix 간 곱셈

array([[ 17.,  22.,  27.],
       [ 22.,  29.,  36.],
       [ 27.,  36.,  45.]])

In [ ]:
print(a)